
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace SampleRegression.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            SampleRegression.ModelInput sampleData = new SampleRegression.ModelInput()
            {
                RMS = 0.12888706F,
                Peak = 0.496F,
                CrestFactor = 3.8483307F,
                Kurtosis = 0.4054385F,
                Skewness = 0.034371573F,
                StdDev = 0.091460794F,
                PeakToPeak = 0.896F,
                Mean = -0.09081186F,
                Variance = 0.008365077F,
                DominantFreq_Hz = 0.625F,
                DominantFreq_Mag = 0.06942102F,
                Energy_0_500Hz = 0.08965622F,
                Energy_500_1000Hz = 0.030435402F,
                Energy_1000_2000Hz = 0.036226626F,
                Energy_2000_4000Hz = 0.035744384F,
                Energy_4000_6000Hz = 0.055949595F,
                Energy_6000_8000Hz = 0.045438346F,
                Energy_8000_10240Hz = 0.02949039F,
                Energy_BPFO = 0.005876964F,
                Energy_BPFI = 0.002996857F,
                Energy_BSF = 0.001688202F,
                Energy_FTF = 0.001661243F,
                Energy_BPFO_2x = 0.004570889F,
                Energy_BPFI_2x = 0.003602543F,
                Energy_BPFO_3x = 0.002493057F,
                Energy_BPFI_3x = 0.004424508F,
                Revolutions = 0F,
            };


            Console.WriteLine("Using model to make single prediction -- Comparing actual Label with predicted Label from sample data...\n\n");


            Console.WriteLine($"RMS: {0.12888706F}");
            Console.WriteLine($"Peak: {0.496F}");
            Console.WriteLine($"CrestFactor: {3.8483307F}");
            Console.WriteLine($"Kurtosis: {0.4054385F}");
            Console.WriteLine($"Skewness: {0.034371573F}");
            Console.WriteLine($"StdDev: {0.091460794F}");
            Console.WriteLine($"PeakToPeak: {0.896F}");
            Console.WriteLine($"Mean: {-0.09081186F}");
            Console.WriteLine($"Variance: {0.008365077F}");
            Console.WriteLine($"DominantFreq_Hz: {0.625F}");
            Console.WriteLine($"DominantFreq_Mag: {0.06942102F}");
            Console.WriteLine($"Energy_0_500Hz: {0.08965622F}");
            Console.WriteLine($"Energy_500_1000Hz: {0.030435402F}");
            Console.WriteLine($"Energy_1000_2000Hz: {0.036226626F}");
            Console.WriteLine($"Energy_2000_4000Hz: {0.035744384F}");
            Console.WriteLine($"Energy_4000_6000Hz: {0.055949595F}");
            Console.WriteLine($"Energy_6000_8000Hz: {0.045438346F}");
            Console.WriteLine($"Energy_8000_10240Hz: {0.02949039F}");
            Console.WriteLine($"Energy_BPFO: {0.005876964F}");
            Console.WriteLine($"Energy_BPFI: {0.002996857F}");
            Console.WriteLine($"Energy_BSF: {0.001688202F}");
            Console.WriteLine($"Energy_FTF: {0.001661243F}");
            Console.WriteLine($"Energy_BPFO_2x: {0.004570889F}");
            Console.WriteLine($"Energy_BPFI_2x: {0.003602543F}");
            Console.WriteLine($"Energy_BPFO_3x: {0.002493057F}");
            Console.WriteLine($"Energy_BPFI_3x: {0.004424508F}");
            Console.WriteLine($"Revolutions: {0F}");
            Console.WriteLine($"Label: {0.000463822F}");


            // Make a single prediction on the sample data and print results
            var predictionResult = SampleRegression.Predict(sampleData);

            Console.WriteLine($"\n\nPredicted Label: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
