// This file was auto-generated by ML.NET Model Builder.
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML.Trainers.FastTree;

namespace SampleRegression.ConsoleApp
{
    public partial class SampleRegression
    {
        public const string RetrainFilePath =  @"/Users/jonas/Data/treated/Data completion model data/RUL prediction model data.csv";
        public const char RetrainSeparatorChar = ',';
        public const bool RetrainHasHeader =  true;
        public const bool RetrainAllowQuoting =  false;

         /// <summary>
        /// Train a new model with the provided dataset.
        /// </summary>
        /// <param name="outputModelPath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet"</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        public static void Train(string outputModelPath, string inputDataFilePath = RetrainFilePath, char separatorChar = RetrainSeparatorChar, bool hasHeader = RetrainHasHeader, bool allowQuoting = RetrainAllowQuoting)
        {
            var mlContext = new MLContext();

            var data = LoadIDataViewFromFile(mlContext, inputDataFilePath, separatorChar, hasHeader, allowQuoting);
            var model = RetrainModel(mlContext, data);
            SaveModel(mlContext, model, data, outputModelPath);
        }

        /// <summary>
        /// Load an IDataView from a file path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        /// <returns>IDataView with loaded training data.</returns>
        public static IDataView LoadIDataViewFromFile(MLContext mlContext, string inputDataFilePath, char separatorChar, bool hasHeader, bool allowQuoting)
        {
            return mlContext.Data.LoadFromTextFile<ModelInput>(inputDataFilePath, separatorChar, hasHeader, allowQuoting: allowQuoting);
        }


        /// <summary>
        /// Save a model at the specified path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="model">Model to save.</param>
        /// <param name="data">IDataView used to train the model.</param>
        /// <param name="modelSavePath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet.</param>
        public static void SaveModel(MLContext mlContext, ITransformer model, IDataView data, string modelSavePath)
        {
            // Pull the data schema from the IDataView used for training the model
            DataViewSchema dataViewSchema = data.Schema;

            using (var fs = File.Create(modelSavePath))
            {
                mlContext.Model.Save(model, dataViewSchema, fs);
            }
        }


        /// <summary>
        /// Retrain model using the pipeline generated as part of the training process.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainModel(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"RMS", @"RMS"),new InputOutputColumnPair(@"Peak", @"Peak"),new InputOutputColumnPair(@"CrestFactor", @"CrestFactor"),new InputOutputColumnPair(@"Kurtosis", @"Kurtosis"),new InputOutputColumnPair(@"Skewness", @"Skewness"),new InputOutputColumnPair(@"StdDev", @"StdDev"),new InputOutputColumnPair(@"PeakToPeak", @"PeakToPeak"),new InputOutputColumnPair(@"Mean", @"Mean"),new InputOutputColumnPair(@"Variance", @"Variance"),new InputOutputColumnPair(@"DominantFreq_Hz", @"DominantFreq_Hz"),new InputOutputColumnPair(@"DominantFreq_Mag", @"DominantFreq_Mag"),new InputOutputColumnPair(@"Energy_0_500Hz", @"Energy_0_500Hz"),new InputOutputColumnPair(@"Energy_500_1000Hz", @"Energy_500_1000Hz"),new InputOutputColumnPair(@"Energy_1000_2000Hz", @"Energy_1000_2000Hz"),new InputOutputColumnPair(@"Energy_2000_4000Hz", @"Energy_2000_4000Hz"),new InputOutputColumnPair(@"Energy_4000_6000Hz", @"Energy_4000_6000Hz"),new InputOutputColumnPair(@"Energy_6000_8000Hz", @"Energy_6000_8000Hz"),new InputOutputColumnPair(@"Energy_8000_10240Hz", @"Energy_8000_10240Hz"),new InputOutputColumnPair(@"Energy_BPFO", @"Energy_BPFO"),new InputOutputColumnPair(@"Energy_BPFI", @"Energy_BPFI"),new InputOutputColumnPair(@"Energy_BSF", @"Energy_BSF"),new InputOutputColumnPair(@"Energy_FTF", @"Energy_FTF"),new InputOutputColumnPair(@"Energy_BPFO_2x", @"Energy_BPFO_2x"),new InputOutputColumnPair(@"Energy_BPFI_2x", @"Energy_BPFI_2x"),new InputOutputColumnPair(@"Energy_BPFO_3x", @"Energy_BPFO_3x"),new InputOutputColumnPair(@"Energy_BPFI_3x", @"Energy_BPFI_3x"),new InputOutputColumnPair(@"Revolutions", @"Revolutions")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"RMS",@"Peak",@"CrestFactor",@"Kurtosis",@"Skewness",@"StdDev",@"PeakToPeak",@"Mean",@"Variance",@"DominantFreq_Hz",@"DominantFreq_Mag",@"Energy_0_500Hz",@"Energy_500_1000Hz",@"Energy_1000_2000Hz",@"Energy_2000_4000Hz",@"Energy_4000_6000Hz",@"Energy_6000_8000Hz",@"Energy_8000_10240Hz",@"Energy_BPFO",@"Energy_BPFI",@"Energy_BSF",@"Energy_FTF",@"Energy_BPFO_2x",@"Energy_BPFI_2x",@"Energy_BPFO_3x",@"Energy_BPFI_3x",@"Revolutions"}))      
                                    .Append(mlContext.Regression.Trainers.FastTree(new FastTreeRegressionTrainer.Options(){NumberOfLeaves=15157,MinimumExampleCountPerLeaf=2,NumberOfTrees=4,MaximumBinCountPerFeature=569,FeatureFraction=0.7867159845346218,LearningRate=0.9999997766729865,LabelColumnName=@"Label",FeatureColumnName=@"Features",DiskTranspose=false}));

            return pipeline;
        }
    }
 }
